### ISSUE TITLE
NGINX Configuration causes "502 Bad Gateway"

### ISSUE THREAD

**Issue by RobMahn** [nextcloud/documentation#10115]
On [https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html](url),
in both sample NGINX configurations, we have:
```
upstream php-handler {
    server 127.0.0.1:9000;
    #server unix:/var/run/php/php7.4-fpm.sock;
}
```
This results in returning "502 Bad Gateway".

The solution is to use:
```
upstream php-handler {
	server unix:/var/run/php/php-fpm.sock;
}

```

Note that this solution uses the default PHP version instead of specifying the specific version.

**Comment by joshtrichards** [comment]
Hi Rob,

I agree there is probably room for clarification (there always is!).

Unfortunately, it's not as simple as changing that line in the docs. No matter what we place there it'll create a similar issue for other folks with different Linux distributions (where the default PHP-FPM listener varies) or if their NGINX service is running elsewhere (in a dedicated container or separate host).

There also doesn't seem to be a PHP provided default we can rely on, since every Linux distribution makes its own choices about whether to listen via TCP (`127.0.0.1:9000` or via a UNIX socket - with any number of commonly used paths - whether or not PHP version specific).

So we have differences due to local environments, driven by differing architectures and/or defaults.

Maybe something like the below adjustments would be helpful? Let me know your thoughts.

> * You need to insert the following code into your Nginx configuration file.
> * [...]
> * Adjust the `server` directive under `php-handler` to match your PHP FPM installation's configured listener (see *Tips and Tricks: NGINX php-handler configuration* for details)
> [...]
> `upstream php-handler {`
> `    # This must match your locally configured PHP FPM listen directive (typically found somewhere like /etc/php/8.1/pool.d/www.conf)`
> [...]
> ## Tips and Tricks
> [...]
> ### NGINX PHP-HANDLER
> The `server` line for the `php-handler` needs to be set to reflect your PHP FPM configuration, OS distribution, and local environment. It must match whatever is configured for the `listen` directive within the PHP-FPM pool you'll be using for NC. Many Linux distributions define the listener for a default PHP-FPM pool called `www` in a file called `www.conf` located somewhere like `/etc/php/8.1/pool.d`.
> 
> Look for the line that is set to something like: 
> 
> `listen = /var/run/php/php-fpm.sock` or `127.0.0.1:9000`. 
> 
> If PHP-FPM will be running on the same host as NGINX (it's a safe assumption it will be if you're unsure), it is recommended you use the UNIX socket (i.e. `/var/run/php/php-fpm.sock`) over the TCP (`127.0.0.1:9000`) one for maximum performance (though either will work as long as the NGINX and PHP FPM configurations match).
> 
> After deciding how you'd prefer to connect NGINX with PHP-FPM (and updating your local PHP FPM configuration if necessary), set your NGINX configuration's php-handler `server` to match your preference (Note: If using UNIX sockets, prepend `unix:` in the NGINX configuration, but not in your PHP FPM `www.conf`).

**Comment by RobMahn** [comment]
I understand what you're saying about the various environments.  Any clarification you can provide should be helpful.  I was simply reporting the error that I had found.  Thank you for your support.

**Comment by tflidd** [comment]
@RobMahn Did you create a pull request for your changes?

For "experts", it is obvious, however it was completely missing that this part needs modifications by the user. Thanks to point that out.

**Comment by RobMahn** [comment]
> 

No, I did not make a pull request as I did not feel qualified to make the changes.  I was merely reporting that it did not work in my environment.
