### ISSUE TITLE
configuration error / LDAP

### ISSUE THREAD

**Issue by wrondon-nextcloud** [nextcloud/documentation#11067]
Good afternoon,
Install Nextcloud 26.0.2 I need to integrate it with LDAP but when installing php-ldap it does not allow activating the LDAP user and group backend (This app cannot be installed because the following dependencies are not fulfilled: The library ldap is not available).

All dependencies installed.
Selinux disabled

Rocky 8.8 operating system
php.x86_64  8.0.30-1.el8.remi  
php-ldap.x86_64  8.0.30-1.el8.remi 
Apache 2.4.37

I appreciate any help

**Comment by joshtrichards** [comment]
Hi @wrondon-nextcloud - Would you mind posting this query over at the [Nextcloud Help Forum](https://help.nextcloud.com)?

This channel here is for reporting mistakes or enhancements ideas for the documentation. It's not for general troubleshooting or technical support. 

But if you get your issue worked out and think some clarification is needed in the docs, let us know!

P.S. From the sounds of it, the PHP extension isn't truly active. Might be as simple as your web server (if using `mod_php`) or FPM service needing to be restarted. Otherwise it's not enabled in your Apache or FPM PHP configs or something along those lines. Maybe check the output of `php -i` from the command line to see if ldap shows up listed as actually loaded.

Another way is to check via `phpinfo()` (a PHP script running through your web app server), but it's a few extra steps:

https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html#php-version-and-information
