### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by stone212** [nextcloud/documentation#1142]
On the "instructions" page here: https://docs.nextcloud.com/server/15/admin_manual/maintenance/manual_upgrade.html

you will see this:

```
10. Adjust file ownership and permissions:

chown -R www-data:www-data nextcloud
find nextcloud/ -type d -exec chmod 750 {} \;
find nextcloud/ -type f -exec chmod 640 {} \;
```

Two steps later you have:

```
12. Now launch the upgrade from the command line using occ, like this example on Ubuntu Linux:

sudo -u www-data php occ upgrade
```

The output of this is:

`Could not open input file: occ`

You have to re-set the file permissions to 755 and then you can run this.

**Comment by MorrisJobke** [comment]
> You have to re-set the file permissions to 755 and then you can run this.

The executable bit should not be needed, because it is called with `php` infant, which leaves to permissions like `644` (`755` minus the executable bit), which is then only a diff of the read permission for others, which should not be needed as you are `www-data` and thus the owner. Could you do an `ls -la` in the directory to check what are the specific permissions and owners? Maybe the find command is slightly off.

And on what operating system was this executed?

**Comment by stone212** [comment]
@MorrisJobke 

> Could you do an ls -la in the directory to check what are the specific permissions and owners? Maybe the find command is slightly off.

```
-rw-r-----  1 www-data www-data   283 Jan 11 15:25 occ
```

> And on what operating system was this executed?

Ubuntu 16.04

**Comment by skjnldsv** [comment]
try `sudo -u www-data php ./occ` ?

**Comment by MorrisJobke** [comment]
> @skjnldsv Yes I have tried that (shouldn't matter in this case anyway) and I got the same result. Please read above where the first command works if I set the permissions to 755. So the issue is about file permissions.

We want to understand, why this fails on your system. Do you use SELinux maybe? Because the documented permissions work fine on our systems 😕

**Comment by MorrisJobke** [comment]
In my case it's a Debian and an Ubuntu 16.04 and both work totally fine:

```
root@server:/var/www/html# ls -la
total 160
drwxr-xr-x 14 www-data www-data  4096 Jan 11 17:01 .
drwxrwxrwx 12 root     root      4096 Dec  7 14:36 ..
-rw-r--r--  1 www-data www-data  4078 Jan 11 17:01 .htaccess
-rw-r--r--  1 www-data www-data   163 Jan 11 17:01 .user.ini
drwxr-xr-x 32 www-data www-data  4096 Jan 11 17:01 3rdparty
-rw-r--r--  1 www-data www-data 12063 Jan 11 17:01 AUTHORS
-rw-r--r--  1 www-data www-data 34520 Jan 11 17:01 COPYING
drwxr-xr-x 72 www-data www-data  4096 Jan 11 17:01 apps
drwxr-xr-x  2 www-data www-data  4096 Jan 11 17:01 config
-rw-r--r--  1 www-data www-data  3650 Jan 11 17:01 console.php
drwxr-xr-x 18 www-data www-data  4096 Jan 11 17:01 core
-rw-r--r--  1 www-data www-data  4979 Jan 11 17:01 cron.php
-rw-r--r--  1 www-data www-data   156 Jan 11 17:01 index.html
-rw-r--r--  1 www-data www-data  3172 Jan 11 17:01 index.php
drwxr-xr-x  6 www-data www-data  4096 Jan 11 17:01 lib
-rw-r--r--  1 www-data www-data   283 Jan 11 17:01 occ
drwxr-xr-x  2 www-data www-data  4096 Jan 11 17:01 ocm-provider
drwxr-xr-x  2 www-data www-data  4096 Jan 11 17:01 ocs
drwxr-xr-x  2 www-data www-data  4096 Jan 11 17:01 ocs-provider
-rw-r--r--  1 www-data www-data  2951 Jan 11 17:01 public.php
-rw-r--r--  1 www-data www-data  5139 Jan 11 17:01 remote.php
drwxr-xr-x  4 www-data www-data  4096 Jan 11 17:01 resources
-rw-r--r--  1 www-data www-data    26 Jan 11 17:01 robots.txt
drwxr-xr-x 12 www-data www-data  4096 Jan 11 17:01 settings
-rw-r--r--  1 www-data www-data  2232 Jan 11 17:01 status.php
drwxr-xr-x  3 www-data www-data  4096 Jan 11 17:01 themes
drwxr-xr-x  2 www-data www-data  4096 Jan 11 17:01 updater
-rw-r--r--  1 www-data www-data   362 Jan 11 17:01 version.php
root@server:/var/www/html# sudo -u www-data php occ
Nextcloud 15.0.2

Usage:
  command [options] [arguments]
...
```

**Comment by stone212** [comment]
@MorrisJobke You did not post what command you ran for the chmod.  I showed you my file permissions were different from that after I ran the commands in the howto.

**Comment by MorrisJobke** [comment]
> @MorrisJobke You did not post what command you ran for the chmod. I showed you my file permissions were different from that after I ran the commands in the howto.

I didn't ran any command, but it has the very same permissions, as if I would ran the command.

I highly doubt that the executable flag has influence if a file can be opened or not, because it is the executable flag. Also as this is more a setup issue here I will close it for now and would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by stone212** [comment]
@MorrisJobke 

>I didn't ran any command, but it has the very same permissions, as if I would ran the command.

So you did not even try to duplicate the problem before closing the ticket?  I guess that's normal laziness from a doc team that has screenshots from five versions ago.

> I highly doubt that the executable flag has influence if a file can be opened or not

But you didn't test so your doubt don't mean anything.

> Also as this is more a setup issue here

Right.  Anything you can do to avoid your responsibility to have correct docs.  I see how you work.

> If you wish support with setup issues

I set this up days ago and I explained how I did it.  I logged on here to help you with your documentation errors.  When you get serious about turning out responsible open source tools please contact me and I will help you debug.

**Comment by MorrisJobke** [comment]
> So you did not even try to duplicate the problem before closing the ticket? I guess that's normal laziness from a doc team that has screenshots from five versions ago.

It's not laziness - it's more a "I know what this command does and it results in exactly this". But to defend against this I executed now this command on a Ubuntu 18.04 just for you. And it turns out: it still works here just fine.



> But you didn't test so your doubt don't mean anything.

It does mean something if the command in question is highly unlikely responsible for the symptoms you described. 



> Right. Anything you can do to avoid your responsibility to have correct docs. I see how you work.

That's not what we want to and we will also adjust docs, but we don't adjust docs blindly.



> I set this up days ago and I explained how I did it. I logged on here to help you with your documentation errors. When you get serious about turning out responsible open source tools please contact me and I will help you debug.

Thanks for this, but I don't see that this is the reason and first of all we need to find the reason why it doesn't work in your case. Unfortunately the work here is done on a best effort basis. Everybody here - no matter if employed by the company or part of the community does so. The employees will obviously prioritize requests that come in from paying customers.

It's also not that I didn't tried to help you, but after some steps it turned out to be something else. I hope you can understand that people like me cannot debug every single instance of every person that has a problem endlessly. At some point in time we need to say "sorry, but that's the end of my debugging session, because neither you nor me had a useful trace of where this problem originates". We will help you either on a best effort basis in the forums or you pay someone some money to spend a dedicated time slot together with you - that's the reality. Sorry that we can't give endless support for free here, but my day also just has 24 hours.

**Comment by MorrisJobke** [comment]
One last try: could it be that the dot-files don't have the correct permissions? Espcially the `.htaccess` file? Is it writable by www-data? Because there were such reports in the forum, which where solved by this.

**Comment by MorrisJobke** [comment]
And another one: could you run `pwd` and show the output? And then run `sudo -u www-data php occ` and show the output as well?

**Comment by rullzer** [comment]
@stone212 please be a bit more respectful and understanding. I would like to remind you of our code of conduct https://nextcloud.com/code-of-conduct/

@MorrisJobke has explained why he didn't blindly took over your suggestions. I have tried the steps on the 4 systems I have access to as well and as far as I can tell the docs are correct.

**Comment by stone212** [comment]
@MorrisJobke 

> Thanks for this, but I don't see that this is the reason and first of all we need to find the reason why it doesn't work in your case.

Now you're starting to make sense!

>  At some point in time we need to say "sorry, but that's the end of my debugging session

I agree.  But you didn't *start* to debug.  You just gave up.

> We will help you either on a best effort basis in the forums or you pay someone some money to spend a dedicated time slot together with you - that's the reality

Again I have to remind you that I already have NC working.  *I* am helping *you* to fix your docs not the other way around.

I will do the debug steps when I build a test server to test new NC features.

**Comment by stone212** [comment]
@rullzer We're on GitLab not your website so your CoC does not apply.  I never was rude or violated GL's CoC.  There are people trying to work here.  Please don't waste our time.

**Comment by stone212** [comment]
@MorrisJobke 

> proofed that my claims (even if they were not tested) were correct

This does not make sense.  If you did not test then it is not proof.  It is a belief.

> I still have the opinion, that this specific part with the permission is not wrong. it might be something else.

I agree!  That is why I am helping you debug.

> Our CoC applies wherever our community interacts with each other

No that is not true.  You may not choose the rules when it is not your house.  Anyway no one here was inappropriate to anyone else.  Just you didn't want to fix the docs.

**Comment by jancborchardt** [comment]
@stone212 I actually unlocked this issue again to give you a chance to say sorry. Seems you are not sorry.

Our code of conduct applies in all of our online and offline spaces. This includes all our repositories on Github amd our forum too. And your tone is not welcome in our community.


-------


Sorry to @MorrisJobke and @rullzer that I reopened to let more hateful comments in.
