### ISSUE TITLE
Is there any plans to translate it into other languages?

### ISSUE THREAD

**Issue by jearton** [nextcloud/documentation#1448]
I 'm an user from China. I wish to look a Chinese version of the document.

**Comment by MorrisJobke** [comment]
cc @jospoortvliet

**Comment by tflidd** [comment]
There were several requests for the user documentation and there are some translations in other languages. I even found a tutorial that this could be done with transifex (links should be here or on the forum).

Just from the number of request and the few changes, I would be quite optimistic for the user manual but it surely depends on the community of this language.

The admin manual, there are more changes and in general it would be a good idea for the admin to know a bit of English. And if we have resources, I'd prefer to improve the English version first.

**Comment by jospoortvliet** [comment]
Some people offered to help but the problem is two-fold. First, it is a lot of work, and outdated or wrong documentation is worse than only English documentation so it will need dedicated help - something we as company can only do if there are customers who need and pay for it.

Second, right now, there is nothing set up to handle this - a good automation using for example Transifex would simplify things and perhaps solve point 1, right now it just makes it worse. Making a copy of this repo, translating all and tracking all changes, for example, is a horrible and very inefficient work-around... It would probably go unmaintained quickly which brings us to problem 1 - better only-english than outdated but translated.

So unless somebody is able to set up some automation in Transifex (or knows how to do it) or, of course, has some other automatic solution to sync translations, we really rather not even let volunteers do it.
