### ISSUE TITLE
Remove unmaintained & outdated Or just moved behind paywall

### ISSUE THREAD

**Issue by Ornias1993** [nextcloud/documentation#1857]
In #667 a lot of documentation has been removed.
This was done due to it being "unmaintained & outdated"  without any reference why and what was outdated. Whole pages got removed.

However:
Even in Latest these pages are still (even the first parts are the same) available behind the nextcloud paywall.
Taking into account the responses when people ask questions about these features, which actually still exist,  It seems this was "outdated" and removed just so they could be moved behind a paywall.

**Comment by skjnldsv** [comment]
@rullzer @nickvergessen

**Comment by nickvergessen** [comment]
The workflow documentation was newly build in another location: https://docs.nextcloud.com/server/stable/admin_manual/file_workflows/

The remaining topics target very large instances and are not really needed for home users. Feel free to get in contact with our sales team if you need any of those other docs for your setup.

**Comment by Ornias1993** [comment]
@nickvergessen So you are hereby formally admitting you guys lied and those things where not actually "unmaintained & outdated" but removed because (like @jospoortvliet also inter alia admitted already) removed due to being "not really needed for home users"?

**Comment by nickvergessen** [comment]
They were "unmaintained and outdated" and have there been removed. Afterwards new documentation for those features have been written due to customer demand (which made us aware only that the existing docs didn't work/match anymore).

Anyway, to me it seems you are on the hunt for troubles and unnecessary discussions, so I'm outta here. :wave:

**Comment by Ornias1993** [comment]
@nickvergessen Thats at least a half truth:
At least the publicly available portions on the new portal-based paywalled documentation is precisely (word for word) the same in most cases.
I also tested some parts of the old documentation and a lot (most?) still applies to latest as well... So far it being "outdated".

Shouldn't the burden of proof of it being outdated be on the one committing said commit? Not on the one questioning it? 

"to me it seems you are on the hunt for troubles and unnecessary discussions"
So now come personal attacks? I think it's pretty clear to me who of us is acting in good faith...

**Comment by Ornias1993** [comment]
Okey, I'm done with this. You guys wanted to lie in my face?
Now face it:

- The PR to remove those pages was done on 6 Feb 2018 by a Nextcloud Employee (1)
- It was merged without any comment or significant review within 12 hours by another Employee (2)
- On 27 May 2018 first registration of the paywalled "portal" containing these pages appeared on the way back machine (3)
- The public portion of at least two pages of this portal that where part of the removal is the same (4) (5)

(1) https://github.com/nextcloud/documentation/pull/667#issue-167351203
(2) https://github.com/nextcloud/documentation/pull/667 (No hardlink available)
(3) https://web.archive.org/web/20180527003343/https://portal.nextcloud.com/
(4) https://portal.nextcloud.com/article/4/configuring-single-sign-on-10.html
(5) https://portal.nextcloud.com/article/tagging-and-workflows-32.html

Honesty and Accountability is important in OpenSource.
NOW I've been looking for trouble and discussion, because you where dishonest and need to be held accountable.

**Comment by jospoortvliet** [comment]
> Shouldn't the burden of proof of it being outdated be on the one committing said commit? Not on the one questioning it?

Pfff, just because the boring intro didn't change you don't believe anything changed? Well, that's your right of course, but I fail to see why any of it matters. The docs here are largely meant for home users, for whom we have always done a lot, without getting paid, because we all care a lot about private use of Nextcloud.

But if you are getting paid to set up a Nextcloud server, you can also pay to get access to our knowledge and expertise. Seems a fair deal, right, given all that we give away? I'll close this now as it is a pointless discussion. If you feel like creating a blog post somewhere explaining how people can set up a Nextcloud server for 10.000 users - go ahead, you will certainly save some big company some money that they otherwise might have paid so some engineers get paid to improve Nextcloud.
