### ISSUE TITLE
nginx example configs: minor suggestions/ideas

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/documentation#194]
Reported by @voidzero in https://github.com/nextcloud/server/issues/1552

**Comment by voidzero** [comment]
Which branch should I update? Not sure if I should use stable9, or master.

**Comment by nickvergessen** [comment]
master, we will copy the changes to the other branches afterwards

**Comment by tflidd** [comment]
A short list of change requests:

- [x] gzip compression: https://github.com/nextcloud/documentation/pull/386
- [ ] Permissions of `htaccesstest.txt`
- [ ] Put php setting for upload limit to nginx-config
- [ ] Use temporary redirect for `.well-known/*` redirections

**Comment by joshtrichards** [comment]
- The permissions of htaccesstest.txt is moot due to nextcloud/server/pull/2513 (and there's no need to mess with the example at the moment IMO since it's really just an example for "what to do if you're logs have misc crud in them" - if anything I'd remove that section entirely since it's not NC specific and really just generic NGINX/system admin stuff. Well, or maybe make the example reference a random URL other than htaccesstest.txt I guess so as to avoid confusion)
- upload settings: Submitted PR #10423 to address that
- Temporary redirect stuff is debatable and, in any case, the nginx config is modeled after the core .htaccess which currently uses 301. Any consideration to changing in in the nginx doc would only be a byproduct of doing so in core and there's no serious demand to do so so I'd consider this issue basically closed out.
