### ISSUE TITLE
[Documentation Request] Using fusionauth.io as SSO / Auth Provider

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [nextcloud/documentation#2041]
Please document how one can use fusionauth.io as the SSO/ Auth provider.

**Comment by MorrisJobke** [comment]
Thanks for the request.

If someone will provide this documentation we are happy to add it to our documentation but we will not proactively document this here, because as of now nobody from our team uses it. If there is somebody in the community that uses it, feel free to provide the steps. 


Thus I will close this here for now.
