### ISSUE TITLE
Groupware Documentation

### ISSUE THREAD

**Issue by thromeaway** [nextcloud/documentation#2061]
I couldnt find any documentation about the Groupware settings for example how the push notifications work. Either i overlooked it and its really hard to find or non existant. In both cases it should be easier to find.

**Comment by MorrisJobke** [comment]
> for example how the push notifications work

They should just work. If you want the technical details, then head over to the notifications app: https://github.com/nextcloud/notifications/blob/master/docs/push-v2.md

But in general this is nothing an admin or end user should care about, because it should just work.

Let's close this then, if there is no further question.
