### ISSUE TITLE
Admin Manual as PDF is not accessible

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/documentation#285]
I tried to download [https://docs.nextcloud.com/server/11/Nextcloud_Server_Administration_Manual.pdf](url)

Not possible ... Access forbidden.

But I think it's not a bug for a T-Shirt :-(

**Comment by MorrisJobke** [comment]
Cc @lukasreschke

**Comment by jaakristioja** [comment]
The above broken URL for the PDF is provided by https://docs.nextcloud.com/

PS: I also suggest the filenames for the PDF files be consistent and also contain the Nextcloud version number (so that it would be easier to download manuals for multiple versions into the same folder), e.g. `Nextcloud_11_User_Manual.pdf`, `Nextcloud_11_Server_Administration_Manual.pdf` and `Nextcloud_11_Developer_Manual.pdf`. Currently these seem to be named `Nextcloud_User_Manual.pdf`, `Nextcloud_Server_Administration_Manual.pdf` and `NextcloudDeveloperManual.pdf`.

**Comment by kangaroo72** [comment]
+1

**Comment by nickvergessen** [comment]
Patch in #294 will take 12 hours to be live, after the patch was merged.
