### ISSUE TITLE
Outdated install instructions for CentOS regarding php 5.6

### ISSUE THREAD

**Issue by tflidd** [nextcloud/documentation#291]
lamixer reported this on the forum (https://help.nextcloud.com/t/update-docs-re-php-and-centos/6656):

At this page https://docs.nextcloud.com/server/11/admin_manual/installation/php_55_installation.html you kindly explain how to get PHP5.5 on Centos 7. I'm bringing up a virgin installation of Nextcloud 11 (the current stable release) on Centos 7 1611 just installed.

It is a bit frustrating to go through your installation docs, get PHP5.5.x working at some difficulty (5.4.x being the 'normal' one) only to find upon trying to configure Nextcloud that PHP 5.6 is required!

Please update your docs for Nextcloud 11 to give help/instructions to install a version of PHP on Centos 7 which WILL ACTUALLY WORK! Or, if that is too difficult to advise in short order, then at least update that page of the docs to say you must not install the OS default PHP 5.4 but you must seek out a solution for yourself that yeilds PHP 5.6 +.

Thanks. I wasn't expecting this frustration so early in the install process. First time with Nextcloud, as a former Owncloud user.

**Comment by tflidd** [comment]
Duplicate of https://github.com/nextcloud/documentation/issues/140

**Comment by MorrisJobke** [comment]
Comment by @oparoz:

> Adapt this page to PHP 5.6
https://docs.nextcloud.com/server/10/admin_manual/installation/php_55_installation.html

**Comment by LukasReschke** [comment]
Or if one goes crazy: PHP 7.0 :)

https://access.redhat.com/errata/RHEA-2016:2730

**Comment by oparoz** [comment]
Finally... 
We can recommend Red Hat again :)

**Comment by xMartin** [comment]
While you're at it: https://docs.nextcloud.com/server/11/admin_manual/installation/php_54_installation.html

**Comment by lamixer** [comment]
It's a bit sad no action has been taken on this. Imagine you are an admin of limited experience and you are following the Nextcloud installation manual here: https://docs.nextcloud.com/server/11/admin_manual/contents.html and you get to the section on PHP, follow the instructions, and it doesn't work. 

This is not an 'enhancement' to the docs but a correction, as one assumes following the instructions will yield a working result. Can it at least get assigned to someone? 

I think the section "Installing PHP 5.4 on RHEL 6 and CentOS 6" should be removed because that is not a workable system. Then "Installing PHP 5.5 on RHEL 7 and CentOS 7" section, which is the subject of this request, needs to switch to 5.6 or a newer recommended version. What version do the RHEL/CentOS experts at Nextcloud want people to use?

If there's really no one to do it, maybe I could try it myself. But I feel it is probably as urgent as any other docs update.

**Comment by tflidd** [comment]
Closed with merge of #388
