### ISSUE TITLE
Windows client rewrite rule for Nginx

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/documentation#372]
In server we introduced this to the .htaccess (see https://github.com/nextcloud/server/pull/3370)

```
RewriteCond %{HTTP_USER_AGENT}  DavClnt
RewriteRule ^$         /remote.php/webdav/          [L,R=302]
```

@josh4trunks How can we add this to the Nginx configuration?

**Comment by josh4trunks** [comment]
I don't know of the top of my head, but I think we might need an if statement (which I usually try to avoid).

Maybe we can ping some other nginx people in this thread in case they have experience with this.
@mmattel 
hmm it seems @RealRancor is no longer on github

**Comment by benediktg** [comment]
How about that?
```nginx
if ($http_user_agent = 'DavClnt') {
    return 302 $scheme://$host/remote.php/webdav/;
}
```

**Comment by josh4trunks** [comment]
@benediktg looks good to me
maybe someone with a NC12 using nginx can test.

**Comment by mmattel** [comment]
pls see also https://github.com/owncloud/documentation/pull/2668#issuecomment-259909754
all is described there including the advantages.
I have this running on my nginx server.
Just google, map is better than if ...

**Comment by josh4trunks** [comment]
@mmattel great point, I didn't think to use map!

can it be in a server block? when I've used it is in the http block.

**Comment by josh4trunks** [comment]
ohh you already answered in your post, lol. yes, we'd need to mention the http block which means mentioning another file in the config.
And I also agree with the comment there to drop checking for OPTIONS since it's not in the htaccess.

so, if I understand there is still an If. but it is a Boolean check instead of an equality. I guess that is a bit better but is more difficult to document for some performance/possible security benefit?

**Comment by mmattel** [comment]
@josh4trunks 
conf files are included in the http block by nginx automatically.
The map directive cannot be in the serverblock !
Therefore I proposed to split as in my comment the way of doing.
This btw eases things, because when you add a map directive you just need to do it in the custom conf file and add the query at the right place in the server block.

If you have more than one instance, this way of doing makes things very easy, because if templating and including...

For your reference, here is my common_map.conf
```
# map must be in the http{} block

# owncloud: cache_purge
map $request_uri $skip_cache {
        default                         1;
        ~*thumbnail.php                 0;
        ~*\/apps\/gallery\/             0;
        ~*\/apps\/galleryplus\/         0;
        }

# owncloud: Fixes Windows WebDav client error 0x80070043 "The network name cannot be
 found."
map "$http_user_agent:$request_method" $WinWebDav {
        default                                 0;
        "DavClnt:OPTIONS"               1;
}

# owncloud: do not access log gallery thumbnails, flooding access logs only, error w
ill be logged anyway
map $request_uri $loggable {
        default                                         1;
        ~*\/apps\/gallery\/thumbnails           0;
        ~*\/apps\/galleryplus\/thumbnails       0;
}
```
For the first two maps a description is alrady available 
For the logging I have in the server block the following:
```
access_log /var/log/nginx/owncloud.access_log combined if=$loggable;
```

**Comment by benediktg** [comment]
> conf files are included in the http block by nginx automatically.

But only if you have a line like
```nginx
include conf.d/*.conf;
```
somewhere in the `http` block of your `/etc/nginx/nginx.conf`. :wink:

You also could put the `map` block between e.g. the `upstream php-handler` and the `server` block in the nginx config example.

**Comment by benediktg** [comment]
BTW: I already knew that [if is evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/) and most of the times there are better ways to [convert rewrite rules](https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/). But I thought that because it's just a single condition a simple `if` block (without `map`) would be sufficient and assumed that the performance should not be that different. ;)

**Comment by josh4trunks** [comment]
wow you really like map, couldn't those request_uri be handled by location. or is map clreaner/faster in you opinion?
thanks for bringing this up though, I'm gonna improve my https redirect statement on my config =]

**Comment by josh4trunks** [comment]
For the documentation I think @benediktg solution is simplest.

This would be good but in my opinion a little too messy to document...
```
# To support the Windows WebDAV Client, uncomment the following line and create a map configuration entry
# if ($WinWebDav) { return 302 $scheme://$host/remote.php/webdav/; }
```

Then somewhere relevant document...
```
map "$http_user_agent" $WinWebDav {
  default 0;
  "DavClnt" 1;
}
```

**Comment by mmattel** [comment]
As often,
the easiest looking solution is not always the best.
Following nginx suggestion and all the suggestions in the net, you should use the map way.
The other thing is also working of course.
Maybe you can just reference that this can also be done with map according nginx suggestions.

**Comment by mmattel** [comment]
Add note, it is not about having one if statement, but if this is a bigger environment, map is the way to go.
(And I like if we help people to follow the vendors suggestion removing issues from the beginning).
Just my 2c :smile:

**Comment by benediktg** [comment]
> Following nginx suggestion and all the suggestions in the net, you should use the map way.

But what exactly is wrong with `if ($http_user_agent = …)` ? *If is evil* says (emphasis by me)
> Directive if has problems when used *in location context*, in some cases it doesn’t do what you expect but something completely different instead.
> …
> There are cases where you simply *cannot avoid using an if*, for example, if you need to test a variable which has no equivalent directive.

Because 1) this is not in a `location` context\* and 2) there is no elegant declarative equivalent for that I think this plain `if` without map is OK.

\*wait, if Nextcloud is installed inside a subdir, then it might be and it should be noted that you should not do `if` inside `location`

**Comment by mmattel** [comment]
I did not wanted to explode the tread, sorry if this turns so.
Because asked, just wanted to give you another pov and how I solved it.

**Comment by joshtrichards** [comment]
Can be closed - this issue appears to have made it into the latest docs already: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

**Comment by tflidd** [comment]
> Can be closed - this issue appears to have made it into the latest docs already: https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

👍
