### ISSUE TITLE
(little bit) Hardening with GeoIP block for documentation

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/documentation#395]
Would be nice to insert that point into "Hardening and Security Guidance". People searching for "hardening nextcloud" will forwardes to that documents.

Perhaps there are more easy hardenings?

I know there are a lot of exceptions like VPN, if supported by webhoster and perhaps not working with Amazon/Google/Dropbox drives. But it is a small step

For all-inkl webhoster and .htaccess/Apache copy simple that code to your .htacces to block all countries instead of Germany

### Whitelist
(all countries blocked instead of exception)

> GeoIPEnable On
Order deny,allow 
Deny from all #
Allow from env=Whitelist
SetEnvIf GEOIP_COUNTRY_CODE DE Whitelist

### Blacklist
(all countries allowed instead of exception)

> GeoIPEnable On
Order deny,allow 
Deny from all #
Deny from env=Blacklist
SetEnvIf GEOIP_COUNTRY_CODE CN Blacklist
SetEnvIf GEOIP_COUNTRY_CODE RU Blacklist
SetEnvIf GEOIP_COUNTRY_CODE LT Blacklist

Here is a list of codes Alpha-2 is working
https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by MariusBluem** [comment]
Oh ... dont know wheter this is a good idea to recommend or even document in the security hardenings section. It is very advanced and could brick much stuff (Federation, ...) - Who really wants to do such things, does not search for that in our documentation I guess 🙈

But what do you think @MorrisJobke

**Comment by Bullnados** [comment]
WHAT, I always searching(googling) "hardening nextcloud"^^

**Comment by MorrisJobke** [comment]
> Oh ... dont know wheter this is a good idea to recommend or even document in the security hardenings section. It is very advanced and could brick much stuff (Federation, ...) - Who really wants to do such things, does not search for that in our documentation I guess 🙈

Right ... didn't thought of this :/ But I guess this is right and counter intuitive.

**Comment by Bullnados** [comment]
I understand your point of view. Some keywords in a seperate menu item with a warning would also be enought. 
Atm a lot of news were published about security topics and the GeoIP is a small step in the right direction. Of course there will be some more interesting keywords for hardening.

**Comment by MariusBluem** [comment]
However... This is more something for hardening your webserver than a really Nextcloud specific topic.
The risk, that people would simply do this for a small or simply no reason is to high if we document this directly here.

GeoIP is not something we should promote over here, because it causes problems with our updater (e.g. server located currently in Germany - so instances from the United States will not longer receive updates if they use the whitelist-method), federation (or sharing in general) and apps like Mail (reaching Mail-servers in other countries) , Calendar (Subscriptions), Video calls (with people from other countries) ... nobody thinks of first, and a user will not receive a proper feedback 😁 

The problem is not about admins who really know what they do and rely on this GeoIP-block for company policy reasons or military-grade instances 😜 for example. They know what they are doing, and they probably also know already how to do this. And if not - they should look for an documentation of their webserver (apache) 😉 

The problem is the normal "beginner" who wants to make his instance as secure as possible - by not paying attention on the big downsides. He will setup this GeoIP stuff, ... and then - he - or one of his users having problems with one of the features (or anything other) mentioned above - does not know what to do. 

Closing here. But you are welcome to contribute a Guide in our forums how-to section: https://help.nextcloud.com/c/How-to-FAQs

**Comment by Bullnados** [comment]
Thanks for the explanation. If I found some more usefull .htaccess things :smiley:
