### ISSUE TITLE
opcache for Nextcloud

### ISSUE THREAD

**Issue by ghost** [nextcloud/documentation#450]
I could successfully verify the following opcache-settings for Nextcloud but they differ from [Nextclouds documentation](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/server_tuning.html):

> cli/php.ini

```
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.validate_timestamps=1
opcache.revalidate_freq=1
opcache.save_comments=1
```

> fpm/php.ini

```
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.save_comments=1
```

from my perspective there are differences between the cli and the fpm ini's, so it should be treated different either:

> **_opcache.revalidate_freq_** - Basically put, how often (in seconds) should the code cache expire and check if your code has changed. 0 means it checks your PHP code every single request (which adds lots of stat syscalls). Set it to 0 in your development environment. Production doesn't matter because of the next setting.
> 
> **_opcache.validate_timestamps_** - When this is enabled, PHP will check the file timestamp per your opcache.revalidate_freq value.
> When it's disabled, opcache.revaliate_freq is ignored and PHP files are NEVER checked for updated code. So, if you modify your code, the changes won't actually run until you restart or reload PHP (you force a reload with kill -SIGUSR2).
> Yes, this is a pain in the ass, but you should use it. Why? While you're updating or deplying code, new code files can get mixed with old ones— the results are unknown. It's unsafe as hell.

 
described here:
- [values and params](https://www.scalingphpbook.com/blog/2014/02/14/best-zend-opcache-settings.html)
- configuration: [PHP opcache enabled in both php.ini files (chapter 02)](https://www.c-rieger.de/nextcloud-installation-guide/#c02)

I would suggest and also ask for corrections in the documentation for v.11 and v.12 having regards to the opcache-values i just mentioned. looking forward to your reply ;-)

**Comment by joshtrichards** [comment]
`opcache.validate_timestamps=1` is in effect in both of the above examples (even though it's not in the second one explicitly) since it's an inherited PHP default. I'm not sure disabling it - which I believe was OP's intent for FPM mode - is going to have much benefit since code changes (in production environments) only happen in maintenance mode anyhow. And devs making live changes, well, that's on them. :)

Ref: https://www.php.net/manual/en/opcache.configuration.php

As for `opcache.revalidate_freq=1` well it's already `2` by default in a stock PHP installation. In OP's posted configs, they're setting it to `1` for the CLI and inheriting the default (`2`) for FPM. I don't really see the point/difference.

In any case, I suspect the docs have evolved a bit since this Issue was created 6 years ago (and possibly the PHP defaults). The Nextcloud docs today mention a few possibilities but don't take an explicit stance one way or another:

https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache

We mostly suggest a couple things to look at, encourage using OPcache, and then punt to the official PHP OPcache docs. Seems alright to me.

In the [code](https://github.com/nextcloud/server/blob/b253fe4a6b73c6c23d2b4a4028901f626f159003/apps/settings/lib/Controller/CheckSetupController.php#L483) we only "enforce" (warn really) about a couple of things:

- OPcache is enabled
- opcache.save_comments=1 (which is a default but we need it so we check for it + also we explain that in our docs)
- We can access the OPcache API
- Recommend to raise some values if cache stats indicate more than 90% of max values are being reached

From my perspective this Issue can be closed out.
