### ISSUE TITLE
Better guidance for upgrades between major versions

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/documentation#558]
At the moment the How to upgrade documentation doesn't go into detail on how to upgrade from a much older version (say, 9.x) to the current.

Here's context for a user in this situation:
https://help.nextcloud.com/t/19-manual-updates-really/20133

Docs should be updated so they don't have to ask this.

**Comment by MorrisJobke** [comment]
cc @jospoortvliet @MariusBluem

**Comment by jasonbayton** [comment]
Here's a nice example of how it could look:

![image](https://user-images.githubusercontent.com/3178412/29925958-e02c21ba-8e59-11e7-991c-9c810fcb55af.png)

**Comment by jospoortvliet** [comment]
Yeah, that'd be nice... But it'll be low on my todo list, sorry... Very busy. Perhaps we should just link to nextcloud.com/migration, that is easier and quicker to add! Or ask the ppl in the forum to submit a PR...

**Comment by jasonbayton** [comment]
People on the forum need the official process in order to submit it. Linking to migration is very much an oc>nc process and may lead to more questions so maybe not the best idea given we need to make these types of things unquestionable so people don't end up back on the forums looking for clarity.

**Comment by jospoortvliet** [comment]
Hmm, I thought it was about migration (as you mention releases before the first Nextcloud version, 9.0).

But a table like that would make sense, I don't deny it. Part of the issue is that ppl always should go for the latest patch release, which results in us having to update this table for every release, or be vague (use "9.0.x" instead of "9.0.5").

Of course, versions no longer supported don't get new versions so it is not a crazy amount of work, but still...

In either case, can you try to get someone from the forums to make a PR for this? I can test, if somebody does the work in the web interface of Github - I just don't have time to digg out all the specific old versions etc and the rules with which to built the table are not that hard - latest version to latest version, always...
