### ISSUE TITLE
Cuestion about downloading contacts with WebDav

### ISSUE THREAD

**Issue by FranRM** [nextcloud/documentation#6076]
Is it possible to download or access to the contacts in the same way of the files can?

**Comment by MariusBluem** [comment]
Since this is not really an issue with the documentation and more a user question, I'd like to recommend using our [Nextcloud community forums](https://help.nextcloud.com) for such questions.

> Is it possible to download or access to the contacts in the same way of the files can?

Please note that Nextcloud stores your contacts (CardDAV) and calendar (CalDAV) data in the database.
You can find out more about that over here: https://help.nextcloud.com/t/question-data-file-location-for-contacts-and-calendar-apps-snap-installation/25803

You can download / access your Nextcloud Calendar and Contacts with CalDAV and CardDAV-compatible apps.
Find out more over here: https://docs.nextcloud.com/server/20/user_manual/en/pim/index.html
