### ISSUE TITLE
possible mistake in nginx config?

### ISSUE THREAD

**Issue by cynecx** [nextcloud/documentation#6530]
https://github.com/nextcloud/documentation/blob/0ab53b5b01fbc77dd4e1c6a375f083215d21af48/admin_manual/installation/nginx-root.conf.sample#L117

Shouldn't this regex be: `^(.+?\.php)(/.*|)$` instead? (If the uri has no trailing slash, fastcgi_split_path_info would fail)

cc: @jivanpal (https://github.com/nextcloud/documentation/pull/2197)

**Comment by ypid** [comment]
I was just debugging something and tested this. If the regex does not match Nginx 1.18 sets `$fastcgi_path_info` to an empty string. You can try with:

```Nginx
add_header X-debug "path_info: $path_info";
```

I also found  #795 talking about this and it worked for them. In my eyes there is no actual issue here and this can be closed.

**Comment by jivanpal** [comment]
Not sure how I missed the original notification for this, but there is indeed no issue with the regex not matching when `.php` is not followed by a slash. Refer, for example, to [the Debian default](https://salsa.debian.org/nginx-team/nginx/-/blob/master/debian/conf/snippets/fastcgi-php.conf), which is `fastcgi_split_path_info ^(.+?\.php)(/.*)$`. The reason this works as desired is because of [how `$fastcgi_script_name` is defined](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#var_fastcgi_script_name):

> `$fastcgi_script_name`
> 
> request URI or, if a URI ends with a slash, request URI with an index file name configured by the [`fastcgi_index`](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_index) directive appended to it. [...] When using the [`fastcgi_split_path_info`](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info) directive, the `$fastcgi_script_name` variable equals the value of the first capture set by the directive.
