### ISSUE TITLE
Nextcloud manual has wrong webdav address.

### ISSUE THREAD

**Issue by mrclschstr** [nextcloud/documentation#698]
For details see: https://github.com/nextcloud/documentation/issues/661

> Hello everyone,
> 
> the URL https://example.com/nextcloud/remote.php/dav/files/USERNAME/ does definitly not work. The only working URL is https://example.com/nextcloud/remote.php/webdav/ (like @orangepizza already mentioned). I've tested this with NC 12.0.5 and 13 without receiving meaningful log error messages.
> 
> The funny thing is, that the "correct" URL is shown in the screenshot, whereas the "wrong" URL is stated in the text. See: https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html#mapping-drives-with-windows-explorer.
> 
> Can this issue be reopened?

**Comment by tflidd** [comment]
`https://example.com/nextcloud/remote.php/dav/files/USERNAME/` seems to be the newer one. Not sure if the old scheme was kept for compatibility reasons??

@nickvergessen do you know why there are two paths and which one we should prefer in the documentation?

**Comment by orangepizza** [comment]
the link provied for webdev on installed nextcloud is at the left bottom of main menu, click setting. if we change we should change it too. https://example.com/nextcloud/remote.php/webdav/  .
![screenshot-2018-3-9 files - nextcloud](https://user-images.githubusercontent.com/23009540/37197184-20c6f15c-23bd-11e8-98b0-cfaac479e4d0.png)

**Comment by nickvergessen** [comment]
I think there is no technical difference. `/dav/...` should be the newer one, because that has `calendars` and `addressbooks` next to `files`.

**Comment by orangepizza** [comment]
P.S You should mention that USERNAME on url means you should change it to your nextcloud user name, not left it as-is. it's really easy to miss.
so if I have account named banana on example.org then my webdav address will be
https://example.org/nextcloud/remote.php/dav/files/banana/ , not https://example.org/nextcloud/remote.php/dav/files/USERNAME

**Comment by nickvergessen** [comment]
yeah, should use some more obvious placeholders, maybe `<your-user-id>` or something like that.

**Comment by mrclschstr** [comment]
In the past I had some touble accessing my files with third party application over the new `/dav/...` URL. My latest example is Keepass. I cannot access my database over the new `/dav/...` URL, whereas the old `/webdav/...` URL works like a charm. Seems like there is ideed a technical difference.

Maybe it's my setup, but neither I receive any mealingful error messages within Nextcloud nor in my Apache logs.

**Comment by nickvergessen** [comment]
Summoning @rullzer for dav magic?!

**Comment by orangepizza** [comment]
@mrclschstr @nickvergessen I'm sure its because of people didn't interpret USERNAME as <your username here> and left it unchanged

**Comment by rullzer** [comment]
The old `/webdav` url is still there because else people with old configurations for their clients would all of a sudden crash etc.

You should use the new `remote.php/dav/files/<username>/` path. And if that doesn't work for some reason it is a bug (either in NC or the software using it), but it is hard to judge without any logs etc.

**Comment by mrclschstr** [comment]
I'll try it again with Keepass later. If it fails again, I'll provide some error details.

**Comment by mrclschstr** [comment]
It seems we have a first class [PEBKAC](https://en.wikipedia.org/wiki/User_error)-error here: I retried the database access via the new `/dav/...` URL with Keepass and it works like a charm. I'm so sorry for poking confusion!

Nevertheless: The documentation should be consistent and align with the Nextcloud interface, see https://github.com/nextcloud/documentation/issues/698#issuecomment-371743619.

**Comment by rullzer** [comment]
Very true. Let me shoot in an issue to the server repo

**Comment by c0fe** [comment]
@nickvergessen is this issue still open?

**Comment by FatalMerlin** [comment]
@nickvergessen @rullzer The URL provided to the users for WebDAV access should also be updated.
Is there any update on this?

**Comment by torstenbunde** [comment]
Hello together and as far as this issue seems to be still open just some actual information because I had this problems today!

The server is working with Debian 9.4 and I'm using Nextcloud 13.0.4. The client is Windows 10 Enterprise and just uses the Windows Explorer to integrate WebDAV.

If I use the new URL `https://example.com/nextcloud/remote.php/dav/files/USERNAME/` or even the one on the command line (`net use Z: https://example.com/nextcloud/remote.php/dav/files/USERNAME/ /user:youruser`) it's not possible to connect. The Explorer gives the error message (translated from german):
> https://example.com/nextcloud/remote.php/dav/files/USERNAME/ was inaccessible.
>
> Make sure the name is spelled correctly. There may be a network error. Click Diagnostics to identify and resolve network problems.
>
> (_In german: Auf https://example.com/nextcloud/remote.php/dav/files/USERNAME/ konnte nicht zugegriffen werden. Vergewissern Sie sich, dass der name richtig geschrieben wurde. Möglicherweise besteht ein Netzwerkfehler. Klicken Sie auf "Diagnose", um die Netzwerkprobleme zu identifizieren und zu beheben._)

The attempt on the command line only reports: System error 67 occurred (_in german: Systemfehler 67 aufgetreten_)

I won't get any error message in the Nextcloud server logs and also didn't find anything in the Windows logs! 

But if i use the URL `https://example.com/nextcloud/remote.php/webdav/` everything works fine and without any problems ...

The user I tested this with is a user that authenticates against an Active Directory! If I have a look into the Nextcloud file system I'll find this user with a directory named to his Windows-ID (like `data/ABC12DE3-456F-78G9-HI0J-12KLMN3456O7`) and not his login name. So maybe this is the problem or the old URL is solving this in another way? If I try the new URL `https://example.com/nextcloud/remote.php/dav/files/WINDOWSID/` everything works also fine!

**Comment by FatalMerlin** [comment]
@MorrisJobke Why did you close this? As of my understanding, this issue is not yet completely resoved...

**Comment by MorrisJobke** [comment]
Because #781 fixed it.

**Comment by deadwax** [comment]
No, 781 doesn't appear to fix it, the current situation is ambiguous with one set of directions not working.

The Webdav link given in the files page of nextcloud is:
http://example.com/nextcloud/remote.php/webdav/
This works.

The current manual at:
https://docs.nextcloud.com/server/16/user_manual/files/access_webdav.html
gives instead:
example.com/nextcloud/remote.php/dav/files/USERNAME/
This does not work.
(I'm well aware USERNAME needs to be changed to my user)

This is on NC 16.0.7
