### ISSUE TITLE
PHP: posix and mcrypt shall not be used 

### ISSUE THREAD

**Issue by PackElend** [nextcloud/documentation#783]
Hallo,
according to my research in order to understand the PHP setup I've learned that posix and mcrypt shall not be used.
Details are in my post in the Nextcloud forum: [Real minimum php requirments and some php mistiness](https://help.nextcloud.com/t/real-minimum-php-requirments-and-some-php-mistiness/32991) (Would highly appreciated if someone could my answers there).

regards
stefan

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer @blizzz

**Comment by skjnldsv** [comment]
Bump!

**Comment by joshtrichards** [comment]
- `mcrypt` is long gone and is no longer in the docs
- `posix` is a core php module (you have to go out of your way to compile php yourself and explicitly disable it)

In your linked forum message re: `posix`:
- I have no idea what you're referring to with that Wikipedia entry (https://en.wikipedia.org/wiki/POSIX#Compliant_via_compatibility_feature) for POSIX
- The "warning" on php.net is just saying the `posix_` commands can retrieve sensitive data -- like quite a few others in NC :-)

The `posix_` commands are used by:
- the file scanner
- the check setup controller
- the cron manager
- the console app (occ)
- possible elsewhere (I didn't look outside the server repo)

The `posix` module is definitely required.

You can search the source code yourself: https://github.com/search?q=repo%3Anextcloud%2Fserver+posix_&type=code (to be exhaustive you'd probably want to search all of the nextcloud repos since there are other bits of code not in the server repo)

**Comment by joshtrichards** [comment]
Let's close this and take any follow-up to #784.
