### ISSUE TITLE
Update mail documentation

### ISSUE THREAD

**Issue by rullzer** [nextcloud/documentation#787]
With https://github.com/nextcloud/server/pull/9791 the default php mailer is removed.

Update the docs to reflect this.

**Comment by tflidd** [comment]
To add some more things: Since the current solution was not reliable on certain solutions, I recommended to use ssmtp to forward mail to a real mail server (not possible on hosting solutions of course). That worked quite good and comes close to the solution of installing qmail. However, since ssmtp only sends mail, you don't risk to run a full mail server such as qmail. So I'd like to add that.

Question regarding the changes:
So the default php mode is removed, means we need a new screen shot.

- `smtp` uses swiftmailer to forward mail to a mail server (configuration is done via web-interface)
- `sendmail` will just use the system mailer (qmail, ssmtp, postfix, exim, ...)

**Comment by kesselb** [comment]
Is this still relevant?

**Comment by joshtrichards** [comment]
Taken care of in #903. No references to the old php mailer has existed (in the text or screenshots) for quite some time. Closing.
