### ISSUE TITLE
Consider changes in mariadb utf migration guide due to possible start loop

### ISSUE THREAD

**Issue by godfuture** [nextcloud/documentation#874]
I have explained everything here: https://help.nextcloud.com/t/latest-mariadb-release-broken-with-experimental-utf8mb4-guide/37040

In short, the settings the migration guide offers seems to get deprecated for latest releases of mariadb.  The result is a start loop. Maybe we should give hints for that in the migration guide.

**Comment by joshtrichards** [comment]
This was addressed since this issue was created but apparently not updated here.

Docs no longer include that config. There is a link to some older docs for users with it in it, for those with really older installations, but it's hidden behind a big warning ⚠️ now.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html?highlight=utf8mb4
