### ISSUE TITLE
Missing information about occ files:scan-app-data

### ISSUE THREAD

**Issue by GAS85** [nextcloud/documentation#919]
Hello,
by surfing in tickets I seen one new for me command - `occ files:scan-app-data`, unfortunately it is documented nowhere.
Regards!

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
The command was mostly helpful when manually changing files for debugging reasons and scanning the folder again afterwards. Since we now have a repair step that will make sure that caches are cleared properly, I don't see a reason to highlight the command anymore. cc @rullzer

**Comment by GAS85** [comment]
I will not agree with this. This command was posted as easy solution to issues with previews:
[one](https://github.com/rullzer/previewgenerator/issues/129) and [two](https://github.com/rullzer/previewgenerator/issues/124).

Solutions are
1. https://github.com/rullzer/previewgenerator/issues/94 - Easy - just run commands and re scans - contains information about listed command.
2. https://github.com/rullzer/previewgenerator/issues/96 - Complicated - needs mySQL knowledge and direct access to DB.

My opinion is that as soon as this command can drive to any easy solution with any particular issue - it must be documented.

**Comment by jammon** [comment]
Nextcloud has made great leaps forward since Nextcloud 14, but this issue is still open. 
`occ files:scan-app-data` is widely used in installation instructions and user help in  forums (https://www.google.com/search?q=nextcloud+%22files%3Ascan-app-data%22 , >600 hits), and so I think it is worthy a short explanation what it actually does.
I wondered if I should be using it as some people suggest. But I want to know, what I'm doing.

Thank you for your great work!

**Comment by castillo92** [comment]
Today I found this Issue searching more info about `occ files:scan-app-data`
