### ISSUE TITLE
Setup Environement: Data folder should be outside webroot

### ISSUE THREAD

**Issue by obel1x** [nextcloud/documentation#9415]
in https://docs.nextcloud.com/server/latest/developer_manual/getting_started/devenv.html#gather-information-about-server-setup its not mentioned that the data folder should be outside webroot.

I would suggest using another location from the start, like e.g. the upper directory (would be also better for testing/developing)

**Comment by kesselb** [comment]
I agree for production, but why for development?

**Comment by obel1x** [comment]
to develop for a working production and check, that if every logic works also that way?

**Comment by kesselb** [comment]
Code should not depend on the datadirectory location.
The provided APIs will handle this.

The suggested changes in https://github.com/obel1x/nextcloud-documentation/pull/1 are incomplete. 
If the datadirectory is elsewhere the path must be changed during setup or configuration file.

I'm against this change because it further complicates the development setup.
