### ISSUE TITLE
Document new Apache LimitRequestBody Default

### ISSUE THREAD

**Issue by t-schuster** [nextcloud/documentation#9601]
Apache has changed the default value for LimitRequestBody from 0 to 1 Gigabyte last year (2.4.54 or higher, affects Debian, Ubuntu and the official Docker container). This will break uploads for non-logged in users (such as over share links).

The documentation should be updated in similar light to the Nginx documentation to help users identify issues related to this new default and noting that the default is 1 Gigabyte in newer Apache installations, instead of unlimited as in older installations.

Additionally the documentation should include an official way to update the Docker container's upload limit, as the container is set to a 1 Gigabyte limit by default and the issues related to the Apache bug have not been fixed in almost a year.  Nominally this would be done by bind mounting a configuration file into the container, so an example would be handy for new Administrators attempting an install via Docker.

**Comment by joshtrichards** [comment]
I agree[1].

That parameter became more important now that Apache changed it from unlimited to 1GB.

The page it needs to go on:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

Feel like making an initial attempt at a PR on the page (there's an Edit button)? If you get stuck, don't hesitate to reach out!

[1] Except for the Docker stuff. I presume you're referring to the community micro-service Docker rather than the official AIO Docker. I suggest those doc changes be submitted to  https://github.com/nextcloud/docker/blob/master/README.md.

References:

https://httpd.apache.org/docs/current/mod/core.html#limitrequestbody

https://github.com/nextcloud/docker/issues/1796

https://github.com/nextcloud/server/pull/37696
